// <auto-generated />
using System;
using AvisoRepository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Supermercados.Migrations
{
    [DbContext(typeof(AvisoContexto))]
    partial class AvisoContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AvisoServices.Models.Aviso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localidad_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Producto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Supermercado_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Localidad_id");

                    b.HasIndex("Provincia_id");

                    b.HasIndex("Supermercado_id");

                    b.ToTable("AvisoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comentario = "No queda leche puleva",
                            FechaCreacion = new DateTime(2020, 6, 4, 15, 20, 33, 724, DateTimeKind.Local).AddTicks(9137),
                            Localidad_id = "01",
                            Producto = "leche",
                            Provincia_id = "01",
                            Supermercado_id = "01"
                        },
                        new
                        {
                            Id = 2,
                            Comentario = "No queda galletas de avena",
                            FechaCreacion = new DateTime(2020, 6, 4, 15, 20, 33, 728, DateTimeKind.Local).AddTicks(8934),
                            Localidad_id = "04",
                            Producto = "galletas",
                            Provincia_id = "02",
                            Supermercado_id = "02"
                        },
                        new
                        {
                            Id = 3,
                            Comentario = "No quedan servilletas blancas",
                            FechaCreacion = new DateTime(2020, 6, 4, 15, 20, 33, 728, DateTimeKind.Local).AddTicks(8995),
                            Localidad_id = "07",
                            Producto = "servilletas",
                            Provincia_id = "03",
                            Supermercado_id = "03"
                        });
                });

            modelBuilder.Entity("Supermercados.Models.Localidad", b =>
                {
                    b.Property<string>("Localidad_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Localidad_id");

                    b.HasIndex("Provincia_id");

                    b.ToTable("Localidad");

                    b.HasData(
                        new
                        {
                            Localidad_id = "01",
                            Nombre = "Aljaraque",
                            Provincia_id = "01"
                        },
                        new
                        {
                            Localidad_id = "02",
                            Nombre = "Bonares",
                            Provincia_id = "01"
                        },
                        new
                        {
                            Localidad_id = "03",
                            Nombre = "Cartaya",
                            Provincia_id = "01"
                        },
                        new
                        {
                            Localidad_id = "04",
                            Nombre = "Aguadulce",
                            Provincia_id = "02"
                        },
                        new
                        {
                            Localidad_id = "05",
                            Nombre = "Bormujos",
                            Provincia_id = "02"
                        },
                        new
                        {
                            Localidad_id = "06",
                            Nombre = "Cantillana",
                            Provincia_id = "02"
                        },
                        new
                        {
                            Localidad_id = "07",
                            Nombre = "Algeciras",
                            Provincia_id = "03"
                        },
                        new
                        {
                            Localidad_id = "08",
                            Nombre = "Barbate",
                            Provincia_id = "03"
                        },
                        new
                        {
                            Localidad_id = "09",
                            Nombre = "Ciudad Real",
                            Provincia_id = "03"
                        });
                });

            modelBuilder.Entity("Supermercados.Models.Provincia", b =>
                {
                    b.Property<string>("Provincia_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Provincia_id");

                    b.ToTable("Provincia");

                    b.HasData(
                        new
                        {
                            Provincia_id = "01",
                            Nombre = "Huelva"
                        },
                        new
                        {
                            Provincia_id = "02",
                            Nombre = "Sevilla"
                        },
                        new
                        {
                            Provincia_id = "03",
                            Nombre = "Cadiz"
                        });
                });

            modelBuilder.Entity("Supermercados.Models.Supermercado", b =>
                {
                    b.Property<string>("Supermercado_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Supermercado_id");

                    b.ToTable("Supermercado");

                    b.HasData(
                        new
                        {
                            Supermercado_id = "01",
                            Nombre = "Dia"
                        },
                        new
                        {
                            Supermercado_id = "02",
                            Nombre = "Aldi"
                        },
                        new
                        {
                            Supermercado_id = "03",
                            Nombre = "Mercadona"
                        },
                        new
                        {
                            Supermercado_id = "04",
                            Nombre = "El Jamon"
                        },
                        new
                        {
                            Supermercado_id = "05",
                            Nombre = "Carrefour"
                        });
                });

            modelBuilder.Entity("AvisoServices.Models.Aviso", b =>
                {
                    b.HasOne("Supermercados.Models.Localidad", null)
                        .WithMany()
                        .HasForeignKey("Localidad_id");

                    b.HasOne("Supermercados.Models.Provincia", null)
                        .WithMany()
                        .HasForeignKey("Provincia_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Supermercados.Models.Supermercado", null)
                        .WithMany()
                        .HasForeignKey("Supermercado_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Supermercados.Models.Localidad", b =>
                {
                    b.HasOne("Supermercados.Models.Provincia", null)
                        .WithMany()
                        .HasForeignKey("Provincia_id");
                });
#pragma warning restore 612, 618
        }
    }
}
